kind: Service                             
apiVersion: v1
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: firstapp                    
  type: LoadBalancer
